set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
let path='~/.vim/bundle/Vundle.vim'

call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'dense-analysis/ale'

call vundle#end()            " required
filetype plugin indent on    " required

let g:ale_linters = {
        \   'python': ['flake8', 'pylint', 'bandit', 'pycodestyle'],
        \}
